### ISSUE TITLE
isFALSE(progress): could not find function "isFALSE"

### ISSUE THREAD

**Issue by slerch** [AlexanderHenzi/isodistrreg#1]
When trying to run the usage example under R 3.4.4, the following error message was returned: `Error in isFALSE(progress) : could not find function "isFALSE"`

The base function `isFALSE` appears to have been introduced in R 3.5, so perhaps `Depends: R (>= 3.2)` in `DESCRIPTION` should be changed to `Depends: R (>= 3.5)`.

Best regards, Sebastian

**Comment by AlexanderHenzi** [comment]
Thanks for the hint! I have replaced the dependency by R ( >= 3.5).
